### PR TITLE
[Fixes #77] CLI data parameter

### LINKED ISSUE #77: Add way to start a server with some data using the binary
We want to develop locally in a team using firebase-server as our development databases as not to interfere with each other during development.

I am currently configuring our npm scripts to include

```
"firebase:start": "node ./node_modules/.bin/firebase-server",
"firebase:sync:stag": "firebase use staging && firebase database:get -o ./firebase-server/data.json / && firebase use default",
```

After syncing the datab from remote, I would love to start a server with a given data file. A parameter to a json file would be great for the bin/firebase-server

### PR DESCRIPTION
**Pull request by mediavrog**

### CODE REVIEW

**Comment by urish** [comment]
Thanks for the PR!

Some notes:
1. Let's have separate options for reading from a file vs supplying the data on the command line.
2. Please document the new options in the README file
3. Please fix the eslint issues to make the build past

**Comment by mediavrog** [comment]
Hi @urish 

Thanks for the reply. I will split the options and fix the linting issues.

As for readme, I though as you have the note 

```
For more information, run:

	node_modules/.bin/firebase-server -h
```
in the readme and other options are also not documented, the cli should document itself. Let me know if updating the readme is still necessary

**Comment by mediavrog** [comment]
One question to @urish :

Would you prefer the command to fail if a given file or JSON is invalid, or just start anyway with `{}` as data?

**Comment by urish** [comment]
It should fail in this case. thx!

**Comment by mediavrog** [comment]
@urish Made the changes. If you're good with it, please squash-merge. Cheers

**Comment by urish** [comment]
Looks good - one last thing, can you please document the new options in the `README` file?

**Comment by urish** [comment]
Released as 0.9.0

**Pull request merged**
