### PR TITLE
REST API support

### PR DESCRIPTION
**Pull request by p-salido**
This is an initial pass at implementing the REST API in firebase-server. Looking for feedback before doing whitespace changes etc.

### CODE REVIEW

**Comment by urish** [comment]
First of all, thank you!

Here is my feedback:
1. I would love to see the REST code go into a new module (e.g. `rest.js`), as index.js is already very large.
2. Please also create tests for the new REST code (just as we have tests with the Firebase client code)
3. We need to make this optional - I would add a new parameter to the constructor called "options" that will have a boolean parameter called `restApi`, so the call would look like:
`new FirebaseServer(5000, 'localhost.firebaseio.test', {}, {restApi: true});`

**Comment by p-salido** [comment]
Thanks for the feedback, I will move in the outlined general direction.

**Comment by urish** [comment]
Hi @p-salido, are there any updates so far?

**Comment by p-salido** [comment]
@urish Have not had the bandwidth to make any changes here, but we have been running this diff in local development and testing as well as in circleci and haven't had any issues. Happy to test any changes that you or someone else want to make.

**Comment by p-salido** [comment]
@urish Extracted the code into a separate module.

In light of the recent changes on master, do you still want to add a fourth options parameter to firebase server? I currently have added `rest` option to the first parameter, and #102 has some refactoring of port/options code that's a prerequisite.

**Comment by urish** [comment]
Awesome thing about the refactoring!

We can add the `rest` option in the first parameter, actually, it's preferable this way.

Can you please make sure the indentation is consistent? e.g. [here](https://github.com/urish/firebase-server/pull/95/files#diff-168726dbe96b3ce427e7fedce31bb0bcR115)

**Comment by p-salido** [comment]
@urish Started on tests, am I going about them in a suitable way?

**Comment by p-salido** [comment]
@urish I would like to complete this PR tomorrow, will appreciate your guidance to this end.

**Comment by urish** [comment]
Overall looks good - in the test cases, you should call `done()` in case of failure (e.g. in catch), otherwise the test will timeout.  One approach, for example, is outlined here: http://blog.revathskumar.com/2016/11/javascript-testing-promises.html

**Comment by p-salido** [comment]
@urish Added tests, rest argument to bin/server script, and bind address argument to the server script. Please review.

**Comment by p-salido** [comment]
@urish any thoughts?

**Comment by p-salido** [comment]
@urish ping again

**Comment by urish** [comment]
Hi, thnaks again for all your work on this PR, greatly appreciated!

Have you seen [my comment](https://github.com/urish/firebase-server/pull/95#issuecomment-335004712) regarding catching errors in tests?

**Comment by p-salido** [comment]
@urish I believe I have addressed that.

**Comment by urish** [comment]
I couldn't find it in `http-server.spec.js`, perhaps I missed something or you forgot to push some commits?

**Comment by p-salido** [comment]
@urish Per the bottom of the link you referenced, I am returning promises from it blocks. Does it not work ?

**Comment by urish** [comment]
Hi, so you can either use `done()` or return a promise, but not both:

https://mochajs.org/#working-with-promises

I think the best approach would be just to remove the done callbacks, and use Promises for all the async tests

**Comment by p-salido** [comment]
It says:

> In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception, as this is generally a mistake:

I do not call done.

**Comment by urish** [comment]
The problem is - if in the future somebody changes the code, and there is an error, it will be hard to trace. So even if the tests pass now, they will miss the point of making it easy to catch errors in the future.

Also, we currently use mocha 2.3.3, but as you mentioned, once we switch to a newer version, it will probably fail (you can actually upgrade the mocha version as part of your PR if you wish)

**Comment by p-salido** [comment]
@urish Okay I converted to promises, I had to go offline in the tests to make node quit at the end but it looks like in travis node does not quit anyway. Any ideas?

**Comment by p-salido** [comment]
@urish Okay I converted to promises, I had to go offline in the tests to make node quit at the end but it looks like in travis node does not quit anyway. Any ideas?

**Comment by p-salido** [comment]
@urish Okay I converted to promises, I had to go offline in the tests to make node quit at the end but it looks like in travis node does not quit anyway. Any ideas?

**Comment by p-salido** [comment]
@urish Okay I converted to promises, I had to go offline in the tests to make node quit at the end but it looks like in travis node does not quit anyway. Any ideas?

**Comment by urish** [comment]
Looks good - ready to merge from your end? Or are there still some things you want to work on before I merge?

**Comment by p-salido** [comment]
Good with me, will send follow up PRs if necessary.

**Comment by urish** [comment]
Great!

Thank you for all the time you spent working on this

**Comment by urish** [comment]
Released as 0.12.0

**Pull request merged**
