### PR TITLE
Moving to any-promise instead of native-bluebird

### PR DESCRIPTION
**Pull request by abhishekgahlot**
native-or-bluebird is deprecated. Moved to any-promise
https://github.com/kevinbeaty/any-promise

### CODE REVIEW

**Comment by urish** [comment]
Thanks, this should resolve #37. 

Can this change break for some users?

**Comment by abhishekgahlot** [comment]
I don't think it should. any-promise discover promise available for node less than 0.12. But for more than that its not needed to register. Though I think we should use Bluebird by default given its faster and more compatible with all versions of node.

**Comment by urish** [comment]
You mean, use bluebird instead of `any-promise`?

**Comment by abhishekgahlot** [comment]
Yes, though we already install it. So don't you think any-promise is an extra module.

**Comment by urish** [comment]
`bluebird` is only listen as a devDependency, which means that it won't be available if you simply install `firebase-server` through npm.

I believe that at some point we will simply require node >= 0.12, and then we won't need any-promise or anything similar anymore.

**Pull request merged**
