### PR TITLE
Added callback on close

### LINKED ISSUE #31: Add ws close callback
0.8.1 of ws adds a callback to the close method. It would be useful for firebase-server to allow the passing through of a callback.

Examples of usage would be at the end of a test spec waiting for the server to close and the port to free up before moving on the next spec that might require that port to be free.

If people are happy with this I can make the quick modification and bump the ws version in package.json?

### PR DESCRIPTION
**Pull request by jamiemchale**
Bump ws version to 0.8.1
Added callback to close
Altered README to reflect changes

Closes #31

### CODE REVIEW

**Comment by urish** [comment]
Thanks!

What's the use case?

**Comment by urish** [comment]
N/m, just saw the other issue that you opened with the explanation. Can you please add a test case as well?

**Comment by jamiemchale** [comment]
I have a bunch of Mocha tests that run in sequence. I was closing the server on the after() in each spec, and loading it in the before() in others. Sometimes the close() on the server didn't complete by the time the before() of the next script ran, so a port in use error was raised.

**Comment by jamiemchale** [comment]
Sure, I can have a go. This is one of my first open-source contributions!

**Comment by urish** [comment]
That's wonderful, keep them coming :)

If you need any assistance, feel free to ask

**Comment by jamiemchale** [comment]
The close test was failing on Node v0.10 - it seems that the server wasn't loading in time for the close callback. I'm not sure if there is a tidier or better way of testing this?

**Comment by urish** [comment]
Thanks! Did you try to use `setImmediate` instead of `setTimeout`?

**Comment by urish** [comment]
Released as 0.5.1

**Pull request merged**
