### PR TITLE
Store buffer until websocket frame is complete

### PR DESCRIPTION
**Pull request by abhishekgahlot**
Related to https://github.com/urish/firebase-server/issues/38

Suggestions are appreciated. Thanks!

### CODE REVIEW

**Comment by urish** [comment]
Thanks! 

Can you also add a test case, one that fails before the change and passes thanks to the change?

See `test/server.spec.js` for examples

Thanks!

**Comment by urish** [comment]
Also, please make sure to comply with the project's eslint rules. You can verify your code by running

`npm run lint`

**Comment by abhishekgahlot** [comment]
@urish Can you check now. This test fails on master because of parse error but works on this commit.
Thanks

**Comment by urish** [comment]
Great, thanks!

**Comment by urish** [comment]
Released as 0.5.4

**Comment by abhishekgahlot** [comment]
Thanks! appreciate that.

**Pull request merged**
