### PR TITLE
add tests for priority query

### LINKED ISSUE #12: Priority Queries
Blocker https://github.com/katowulf/mockfirebase/issues/98

(sorry for being short on explanation - I'll flush this out later)

### PR DESCRIPTION
**Pull request by jamestalmage**
Closes #12

### CODE REVIEW

**Comment by urish** [comment]
Thanks! I am now going over all your additions, improving support for running under windows, etc.

Hope to release this soon as 0.4.0

**Comment by urish** [comment]
Hi @jamestalmage, thanks again for all the amazing work!

I noticed the following code lines:

```
			if (normalizedPath.isPriorityPath) {
				throw new Error('I don\'t know how to listen to a priority path');
			}
```

Have you found any scenario that triggers this code path?

**Comment by jamestalmage** [comment]
No. It certainly is possible using a raw websocket, but I don't think the firebase client ever would. It might be a good idea to have the message include   reporting instructions.

If we had control / insight into the client source I might just remove it.

**Comment by urish** [comment]
@jamestalmage the full client source (unminified) is available here:

https://github.com/firebase/firebase-bower/blob/master/firebase-debug.js

If there is no easy way to reproduce this behavior via the client, I think it is better to remove the message...

**Pull request merged**
